# Custom Language File for Launcher Customizer

[ejs.app]
title = "NewSMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le NewSMP"
welcomeDescription = "Utilisez ce launcher pour jouer au serveur"
welcomeDescCTA = "Vous y Ãªtes presque"
