# Custom Language File for Launcher Customizer

[ejs.app]
title = "NewSMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://newsmp.fr"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@NewSMPV3"
mediaDiscordURL = "http://discord.newsmp.fr"

[ejs.settings]
sourceGithubLink = "https://github.com/New-Teams/NewLauncher/"
supportLink = "https://github.com/New-Teams/NewLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le NewSMP"
welcomeDescription = "Utilisez ce launcher pour jouer au serveur"
welcomeDescCTA = "Vous y Ãªtes presque"
