[ejs.landing]
updateAvailableTooltip = "업데이트 있음"
usernamePlaceholder = "닉네임"
usernameEditButton = "수정"
settingsTooltip = "설정"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인"
mojangStatus = "MOJANG 상태"
mojangStatusTooltipTitle = "서비스"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "뉴스"
launchButton = "플레이"
launchButtonPlaceholder = "&#8226; 서버가 선택되지 않았습니다."
launchDetails = "잠시 기다려주세요.."
newsNavigationStatus = "{currentPage} of {totalPages}"
newsErrorLoadSpan = "뉴스 로딩중.."
newsErrorFailedSpan = "뉴스 로딩에 실패했습니다."
newsErrorRetryButton = "다시 시도"
newsErrorNoneSpan = "뉴스 없음"

[ejs.login]
loginCancelText = "취소"
loginSubheader = "마인크래프트 로그인"
loginEmailError = "* 잘못된 형식"
loginEmailPlaceholder = "이메일 또는 닉네임"
loginPasswordError = "* 필수"
loginPasswordPlaceholder = "비밀번호"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "비밀번호를 잊으셨나요?"
loginRememberMeText = "계정 저장"
loginButtonText = "로그인"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "계정이 없으신가요?"
loginPasswordDisclaimer1 = "입력하신 비밀번호는 마이크로소프트에 직접 전송되며 절대 저장되지 않습니다."
loginPasswordDisclaimer2 = "{appName} 는 Mojang AB 와 아무런 관계가 없습니다."

[ejs.loginOptions]
loginOptionsTitle = "로그인 옵션"
loginWithMicrosoft = "마이크로소프트 로그인"
loginWithMojang = "모장 로그인"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "참여 가능한 서버"
serverSelectConfirm = "선택"
serverSelectCancel = "취소"
accountSelectHeader = "계정 선택"
accountSelectConfirm = "선택"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트"
navMods = "모드"
navJava = "자바"
navLauncher = "런처"
navAbout = "정보"
navUpdates = "업데이트"
navDone = "확인"
tabAccountHeaderText = "계정 설정"
tabAccountHeaderDesc = "새 계정을 연동하거나 기존 로그인한 계정을 관리하세요."
microsoftAccount = "마이크로소프트"
addMicrosoftAccount = "+ 마이크로소프트 계정 추가"
mojangAccount = "모장"
addMojangAccount = "+ 모장 계정 추가"
minecraftTabHeaderText = "마인크래프트 설정"
minecraftTabHeaderDesc = "게임 실행과 관련된 옵션입니다."
gameResolutionTitle = "해상도"
launchFullscreenTitle = "전체화면으로 실행"
autoConnectTitle = "실행 시 자동으로 서버에 접속"
launchDetachedTitle = "Launch game process detached from launcher."
launchDetachedDesc = "If the game is not detached, closing the launcher will also close the game."
tabModsHeaderText = "모드 설정"
tabModsHeaderDesc = "모드를 활성화하거나 비활성화하세요."
switchServerButton = "변경"
requiredMods = "필수 모드"
optionalMods = "선택 가능 모드"
dropinMods = "드래그 해 모드 추가"
addMods = "모드 추가"
dropinRefreshNote = "(F5를 눌러 새로고침하세요)"
shaderpacks = "쉐이더팩"
shaderpackDesc = "쉐이더팩를 활성화하거나 비활성화하세요. 원하는 커스텀 쉐이더팩를 추가할 수도 있습니다. 참고 : 고사양 데스크톱에서 사용을 권장합니다."
selectShaderpack = "쉐이더팩 선택"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "자바 설정을 관리하세요. (고급 설정)"
memoryTitle = "메모리"
maxRAM = "최대 메모리"
minRAM = "최소 메모리"
memoryDesc = "권장되는 최소 메모리 값은 3GB입니다. 최소값과 최대값을 같게 설정하면 랙을 줄일 수 있습니다."
memoryTotalTitle = "합계"
memoryAvailableTitle = "사용 가능"
javaExecutableTitle = "자바 런타임"
javaExecSelDialogTitle = "자바 런타임을 선택하세요."
javaExecSelButtonText = "파일 선택"
javaExecDesc = "자바 런타임은 게임 시작 전에 점검됩니다."
javaPathDesc = "경로는 <strong>{pathSuffix}</strong> 로 끝나야 합니다."
jvmOptsTitle = "추가 JVM 설정"
jvmOptsDesc = "런타임 시 JVM에 제공되는 설정입니다. <em>-Xms</em> 와 <em>-Xmx</em> 는 포함되어서는 안됩니다."
launcherTabHeaderText = "런처 설정"
launcherTabHeaderDesc = "런처와 관련된 설정들입니다."
allowPrereleaseTitle = "Pre-Release 업데이트 받기."
allowPrereleaseDesc = "Pre-Releases 에는 완전히 테스트되지 않았거나 통합되지 않았을 수 있는 새로운 기능들이 포함되어 있습니다.<br>Pre-Release 버전을 사용중인 경우 이는 항상 사용됩니다."
dataDirectoryTitle = "데이터 폴더"
selectDataDirectory = "데이터 폴더 선택"
chooseFolder = "폴더 선택"
dataDirectoryDesc = "모든 게임 파일과 로컬 Java 설치는 데이터 폴더에 저장됩니다.<br>스크린샷과 월드 세이브는 해당 서버 구성의 인스턴스 폴더에 저장됩니다."
aboutTabHeaderText = "정보"
aboutTabHeaderDesc = "현재 버전에 대한 정보와 릴리스 노트를 확인하세요."
aboutTitle = "{appName}"
stableRelease = "Stable Release"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "지원"
devToolsConsole = "DevTools Console"
releaseNotes = "릴리스 노트"
changelog = "변경 로그"
noReleaseNotes = "릴리스 노트 없음"
viewReleaseNotes = "GitHub에서 릴리스 노트 보기"
launcherUpdatesHeaderText = "런처 업데이트"
launcherUpdatesHeaderDesc = "런처 업데이트를 다운로드, 설치 및 검토하세요."
checkForUpdates = "업데이트 확인하기"
whatsNew = "새로운 내용"
updateReleaseNotes = "업데이트 릴리스 노트"

[ejs.waiting]
waitingText = "마이크로소프트의 응답을 기다리는중.."

[ejs.welcome]
continueButton = "다음"


[js.discord]
waiting = "클라이언트 대기중.."
state = "서버: {shortId}"

[js.index]
microsoftLoginTitle = "마이크로소프트 로그인"
microsoftLogoutTitle = "마이크로소프트 로그아웃"

[js.login]
login = "로그인"
loggingIn = "로그인중"
success = "완료"
tryAgain = "재시도"

[js.login.error]
invalidValue = "* 잘못된 형식"
requiredValue = "* 필수"

[js.login.error.unknown]
title = "로그인 중 알수없는 오류가 발생했습니다!"
desc = "알 수 없는 오류가 발생했습니다. 자세한 내용은 콘솔을 참조하세요."

[js.landing.launch]
pleaseWait = "잠시 기다려주세요.."
failureTitle = "실행 중 오류 발생"
failureText = "자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."
okay = "확인"

[js.landing.selectedAccount]
noAccountSelected = "아무 계정도 선택되지 않음"

[js.landing.selectedServer]
noSelection = "아무 서버도 선택되지 않음"
loading = "로딩중.."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
checking = "시스템 정보 확인중.."
noCompatibleJava = "호환되는 자바 런타임이 없습니다!"
installJavaMessage = "마인크래프트를 시작하려면 자바 {major}의 64비트 설치가 필요합니다. 설치하시겠습니까?"
installJava = "자바 설치"
installJavaManually = "수동 설치"
javaDownloadPrepare = "자바 다운로드 준비중.."
javaDownloadFailureTitle = "자바 다운로드 중 오류가 발생했습니다!"
javaDownloadFailureText = "자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."
javaRequired = "실행하기 위해<br>자바 런타임이 필요합니다"
javaRequiredMessage = '실행하려면 Java {major}의 유효한 x64 설치가 필요합니다.<br><br>자세한 내용은 <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">자바 관리 가이드</a>를 참조하세요. 자바를 수동으로 설치하는 방법에 대한 영어 가이드입니다.'
javaRequiredDismiss = "확인"
javaRequiredCancel = "돌아가기"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK 배포판을 찾지 못했습니다."
javaDownloadCorruptedError = "다운로드한 JDK에 잘못된 해시가 있으므로 파일이 손상되었을 수 있습니다."
extractingJava = "압축 푸는중.."
javaInstalled = "자바 설치가 완료되었습니다!"

[js.landing.dlAsync]
loadingServerInfo = "서버 정보 확인중.."
fatalError = "치명적 오류"
unableToLoadDistributionIndex = "배포 색인의 복사본을 로드할 수 없습니다. 자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."
pleaseWait = "잠시 기다려주세요.."
errorDuringLaunchTitle = "실행 중 오류 발생"
seeConsoleForDetails = "자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."
validatingFileIntegrity = "파일 무결성을 확인하는 중.."
errorDuringFileVerificationTitle = "파일 확인 중 오류 발생"
downloadingFiles = "파일 다운로드중.."
errorDuringFileDownloadTitle = "파일 다운로드 중 오류 발생"
preparingToLaunch = "실행 준비중.."
launchingGame = "게임 실행중.."
launchWrapperNotDownloaded = "기본 파일인 LaunchWrapper를 제대로 다운로드하지 못했습니다. 결과적으로 게임을 시작할 수 없습니다.<br><br>이 문제를 해결하려면 바이러스 백신 소프트웨어를 일시적으로 끄고 게임을 다시 시작하십시오.<br><br>시간이 있으시면 <a href=\" https://github.com/dscalzi/HeliosLauncher/issues\">문제를 제출</a>하고 사용하는 바이러스 백신 소프트웨어를 알려주세요. 제출해주시면 해당 소프트웨어 관계자에게 연락해서 문제를 바로잡도록 노력할 것입니다."
doneEnjoyServer = "완료되었습니다. 즐거운 시간 보내세요!"
checkConsoleForDetails = "자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."

[js.landing.news]
checking = "뉴스 확인중"

[js.landing.discord]
loading = "게임 로딩중.."
joining = "잡식으로 여행가는중!"
joined = "도착!"

[js.overlay]
dismiss = "무시"

[js.settings.fileSelectors]
executables = "실행 파일"
allFiles = "모든 파일들"

[js.settings.mstfLogin]
errorTitle = "문제가 발생했습니다."
errorMessage = "Microsoft 인증에 실패했습니다. 다시 시도해 주세요."
okButton = "확인"

[js.settings.mstfLogout]
errorTitle = "문제가 발생했습니다."
errorMessage = "Microsoft 로그아웃에 실패했습니다. 다시 시도해 주세요."
okButton = "확인"

[js.settings.authAccountSelect]
selectButton = "계정 선택"
selectedButton = "선택된 계정 &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "경고<br>이것이 마지막 계정입니다"
lastAccountWarningMessage = "런처를 사용하려면 하나 이상의 계정에 로그인해야 합니다. 이후에는 다시 로그인해야 합니다.<br><br>로그아웃하시겠습니까?"
confirmButton = "로그아웃"
cancelButton = "취소"

[js.settings.authAccountPopulate]
username = "닉네임"
uuid = "UUID"
selectAccount = "계정 선택"
selectedAccount = "선택된 계정 ✓"
logout = "로그아웃"

[js.settings.dropinMods]
removeButton = "제거"
deleteFailedTitle = "드롭인 모드<br>{fullName}을(를) 삭제하지 못했습니다."
deleteFailedMessage = "파일이 사용 중이 아닌지 확인하고 다시 시도하세요."
failedToggleTitle = "하나 이상의 드롭인 모드를<br>전환하지 못했습니다."
okButton = "확인"

[js.settings.serverListing]
mainServer = "기본 서버"

[js.settings.java]
selectedJava = "선택됨: 자바 {version} ({vendor})"
invalidSelection = "잘못된 선택"
requiresJava = "자바 {major} x64가 필요합니다."
availableOptions = "자바 {major}(HotSpot VM)에 사용 가능한 설정"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "릴리스 노트 로딩에 실패했습니다."

[js.settings.updates]
newReleaseTitle = "새로운 클라이언트가 있습니다"
newPreReleaseTitle = "새로운 클라이언트 Pre-release 가 있습니다"
downloadingButton = "다운로드중.."
downloadButton = 'GitHub에서 다운로드<span style="font-size: 10px;color: grey;text-shadow: none !important;">런처를 닫고 dmg를 실행하여 업데이트하세요.</span>  '
latestVersionTitle = "최신 버전 클라이언트 실행중"
checkForUpdatesButton = "업데이트 확인"
checkingForUpdatesButton = "업데이트 확인중.."

[js.uibinder.startup]
fatalErrorTitle = "치명적인 오류: Distribution Index를 로드할 수 없습니다."
fatalErrorMessage = "Distribution Index를 다운로드하기 위해 서버에 연결을 설정할 수 없습니다. 로드할 수 있는 로컬 복사본이 없습니다. <br><br>Distribution Index는 최신 서버 정보를 제공하는 필수 파일입니다. 런처가 없으면 런처를 시작할 수 없습니다. 인터넷에 연결되어 있는지 확인하고 애플리케이션을 다시 실행하세요."
closeButton = "닫기"

[js.uibinder.validateAccount]
failedMessageTitle = "로그인을 새로고침 하지 못했습니다."
failedMessage = "<strong>{account}</strong>에 대한 로그인을 새로고침 할 수 없습니다. 다른 계정을 선택하거나 다시 로그인하세요."
failedMessageSelectAnotherAccount = "<strong>{account}</strong>에 대한 로그인을 새로고침 할 수 없습니다. 다시 로그인해주세요."
loginButton = "로그인"
selectAnotherAccountButton = "다른 계정 선택"

[js.uicore.autoUpdate]
checkingForUpdateButton = "업데이트 확인중..."
installNowButton = "설치"
checkForUpdatesButton = "업데이트 확인"
